#'Compute wordCloud of the input entities
#'@description compute wordCloud of the list of entities. The function wraps around the main steps of \pkg{\link{tm}} to wordCloud.
#'@usage computeNodeWordCloud(txtinput, nodetype, annotation, internalid)
#'@param txtinput a character vector of entities e.g. c('pubchemId1', 'pubchemId2').
#'The value can be neo4j ids or grinn ids, see details and see \code{\link{convertId}} for how to convert ids.
#'For Mesh annotation, PubChem CIDs are required.
#'@param nodetype a string specifying a node type. It can be one of compound (default), protein, gene, pathway, rna, dna.
#'@param annotation a string specifying the annotation type e.g. pathway (default) and mesh. Pathway annotation requires the database.
#'Mesh annotation doesn't require the database but it is available for PubChem compounds only.
#'@param internalid a logical value indicating whether \code{txtinput} is the neo4j id, if TRUE (default). If not, \code{txtinput} is expected to be the grinn id or PubChem CID.
#'See details and see \code{\link{convertId}} for how to convert ids. It has no effect on Mesh annotation.
#'@details The database uses two id systems. The neo4j id is a numeric, internal id automatically generated by the database system.
#'The grinn id (gid) is an id system of Grinn database that uses main ids of standard resources
#'i.e. ENSEMBL for genes (e.g.ENSG00000139618), UniProt for proteins (e.g.P0C9J6), PubChem CID for compounds (e.g.5793), KEGG for pathways (e.g.hsa00010).
#'@return list of data frame of nodes, edges and wordcloud. The nodes data frame contains input attributes. The edges data frame contains annotation pairs.
#'The data frame of wordcloud contains the following components:
#'
#'\code{rank} = rank sort by freq
#'
#'\code{id} = annotation id or annotation neo4j id
#'
#'\code{gid} = annotation id or annotation grinn id
#'
#'\code{nodename} = annotation name
#'
#'\code{nodelabel} = annotation type
#'
#'\code{nodexref} = cross references
#'
#'\code{freq} = frequency or number of input entities in each annotation term
#'
#'\code{member} = list of members of the annotation term
#'
#'Return list of empty data frame if error or found nothing.
#'@author Kwanjeera W \email{kwanich@@ucdavis.edu}
#'@references http://www.sthda.com/english/wiki/text-mining-and-word-cloud-fundamentals-in-r-5-simple-steps-you-should-know
#'@seealso \pkg{\link{tm}}, \pkg{\link{wordcloud}}
#'@examples
#'#txtinput <- c(1110,10413,196,51,311,43,764,790) #compute wordCloud for given pubchem compounds
#'#result <- computeNodeWordCloud(txtinput=txtinput, nodetype="compound", annotation="mesh", internalid=FALSE)
#'#wordcloud::wordcloud(words = result$wordcloud$nodename, freq = result$wordcloud$freq, scale=c(2,.1),min.freq = 1,max.words=50, random.order=FALSE, rot.per=0.5, colors=RColorBrewer::brewer.pal(8, "Dark2"))
#'#barplot(result$wordcloud$freq[1:10], las = 2, names.arg = result$wordcloud$nodename[1:10], col ="lightblue", main ="Most frequent words", ylab = "Word frequencies")
#'@export
computeNodeWordCloud <- function(txtinput, nodetype="compound", annotation="pathway", internalid = TRUE) UseMethod("computeNodeWordCloud")
#'@export
computeNodeWordCloud.default <- function (txtinput, nodetype="compound", annotation="pathway", internalid = TRUE){
  out <- tryCatch(
    {
      tmparg <- try(nodetype <- match.arg(tolower(nodetype), c("compound","protein","gene","rna","dna"), several.ok = FALSE), silent = TRUE)
      if (class(tmparg) == "try-error") {
        stop("argument 'nodetype' is not valid, choose one from the list: compound,protein,gene,rna,dna")
      }
      tmparg <- try(annotation <- match.arg(tolower(annotation), c("pathway","mesh"), several.ok = FALSE), silent = TRUE)
      if (class(tmparg) == "try-error") {
        stop("argument 'annotation' is not valid, choose one from the list: pathway,mesh")
      }
      if (class(txtinput) == "data.frame") {#get result from statistical analysis
        if(!is.null(txtinput$PubChem)){
          txtinput = txtinput$PubChem
        }else if(!is.null(txtinput$uniprot)){
          txtinput = txtinput$uniprot
        }else if(!is.null(txtinput$ensembl)){
          txtinput = txtinput$ensembl
        }
      }
      txtinput = unique(stringr::str_trim(unlist(txtinput))) #remove whiteline, duplicate
      txtinput = txtinput[!is.na(txtinput)]
      if(tolower(annotation) == 'pathway' && foundDb()){#pathway wordcloud
        cat("Querying database ...\n")
        if(internalid){
          annols = lapply(txtinput, function(x) fetchNetwork(to=x, fromtype="pathway", totype = nodetype, reltype = "ANNOTATION")) #query annotation pairs
        }else{
          annols = lapply(txtinput, function(x) fetchNetworkByGID(to=x, fromtype="pathway", totype = nodetype, reltype = "ANNOTATION")) #query annotation pairs
        }
        if(!is.null(unlist(annols))){#found annotation
          annonws = combineNetworks(annols) #combine annotation pairs
          wc = callWordCloud(edgelist = annonws$edges, nodelist = annonws$nodes) #compute wordcloud
          wc = wc[order(wc$freq, decreasing = TRUE),]
          wc$rank = seq(1:nrow(wc))
          wc = wc[,c(ncol(wc),1:(ncol(wc)-1))] #rearrange columns
          networknode = annonws$nodes[annonws$nodes$nodelabel != "Pathway", ] #not return pathway nodes
          list(nodes=networknode, edges=annonws$edges, wordcloud=wc) #output
        }
        else{#no annotation found
          list(nodes=data.frame(), edges=data.frame(), wordcloud=data.frame()) #output
        }
      }else if(tolower(annotation) == 'mesh'){#mesh wordcloud
        if(internalid || tolower(nodetype) != "compound"){
          cat("Error: Accept only PubChem compounds, returning no data ...\n")
          annols = NULL
        }else{
          cat("Connecting PubChem ...\n")
          annols = lapply(txtinput, function(x) callMesh(pcid=x)) #query pubchem annotation pairs
        }
        if(!is.null(unlist(annols))){#found annotation
          annonws = combineNetworks(annols) #combine annotation pairs
          if(foundDb()){#have db
            nodels = lapply(txtinput, formatNode.LIST, y="compound", z="grinnid") #query nodes by gid
            networknode = plyr::ldply(nodels, data.frame)
            networknode$id = networknode$gid
          }else{#no db
            cat("No database installed, returning original input ...\n")
            networknode = data.frame(id=txtinput, gid=txtinput, nodename=txtinput, nodelabel="Compound", nodexref='', stringsAsFactors = FALSE)
          }
          wc = callWordCloud(edgelist = annonws$edges, nodelist = annonws$nodes) #compute wordcloud
          wc = wc[order(wc$freq, decreasing = TRUE),]
          wc$rank = seq(1:nrow(wc))
          wc = wc[,c(ncol(wc),1:(ncol(wc)-5),(ncol(wc)-2),(ncol(wc)-1))] #rearrange columns
          list(nodes=networknode, edges=annonws$edges, wordcloud=wc) #output
        }else{#no annotation found
          list(nodes=data.frame(), edges=data.frame(), wordcloud=data.frame()) #output
        }
      }else{
        cat('Error: No database installed, returning no data ..\n')
        list(nodes=data.frame(), edges=data.frame(), wordcloud=data.frame()) #output
      }
    },error=function(e) {
      message(e)
      cat("\nError: RETURN no data ..\n")
      list(nodes=data.frame(), edges=data.frame(), wordcloud=data.frame()) #output
    })
  return(out)
}
